DROP TRIGGER IF EXISTS ArticleBeforeEdition;
DELIMITER //
CREATE TRIGGER ArticleBeforeEdition
BEFORE INSERT ON Article FOR EACH ROW
BEGIN
IF NEW.ArticleDate < NEW.PubDate THEN SET NEW.ArticleDate = '0000-00-00 00:00:00';
END IF;
END//
DELIMITER ;